name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env File for Web
        run: |
          touch apps/web/.env
          echo BASE_PATH=/permata-aksesoris >> apps/web/.env
      - name: Create .env File for API
        run: |
          touch apps/api/.env
          echo PORT=3002 >> apps/api/.env
          echo DB_NAME=permata_aksesoris >> apps/api/.env
          echo DB_HOST=permata-aksesoris-database >> apps/api/.env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> apps/api/.env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> apps/api/.env
          echo DB_PORT=3306 >> apps/api/.env
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        run: |
          npm install
          npx nx build web
          npx nx build:image web
          npx nx build:linux api
          npx nx build:image api
      - name: Push Image
        run: |
          npx nx push:image web
          npx nx push:image api
      - name: Deploy Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/Deployments/permata-aksesoris
            docker compose stop
            docker compose pull
            docker compose up -d
