name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        run: |
          npm install
          npx nx build web
          npx nx build:image web
          npx nx build:linux api
          npx nx build:image api
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/permata-aksesoris-web
          docker push ${{ secrets.DOCKER_USER }}/permata-aksesoris-api
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/Deployments/permata-aksesoris
            git pull origin main
            docker compose up
